### ISSUE TITLE
Ready for test

### ISSUE THREAD

**Issue by gerard33** [gerard33/sony-bravia-ha#1]
Hi @mm7d

The first version of the `braviatv` component which supports both PIN and PSK is ready for testing.
https://github.com/gerard33/sony-bravia-ha/blob/master/braviatv_psk.py
I have run this version with PSK for my TV without problems.

I have also added your WOL on multiple NICS PRs https://github.com/gerard33/sony_bravia_psk/pull/1 and https://github.com/gerard33/home-assistant/pull/2 in this version.

Can you test:
- [ ] PSK method
- [ ] PIN method
- [ ] WOL with the new broadcast method

This component is currently getting the bravia library from my Github. Once you can confirm everything is working okay I will put the library on PyPi.

**Comment by mm7d** [comment]
I am really busy math the moment,
I wil try to test tonight or this sunday.

Martijn

**Comment by gerard33** [comment]
No hurries :)

**Comment by mm7d** [comment]
I have tested the latest version and all seems ok!

Sorry for the delay, I have been extremely busy lately.

Martijn

**Comment by gerard33** [comment]
@mm7d is the new version still working okay?

Can you confirm that the PIN method is still working fine with this version?
I want to know this for sure before making a PR for this on HA.

**Comment by mm7d** [comment]
I actually run pin, at the moment, no problems!

Verstuurd vanaf mijn iPad
